### ISSUE TITLE
Check "gren" if this is possible

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Git-Release-Notes#2]
Let's assume we have a `develop` branch from which we cut BETA releases. There is also a 'master' branch where we more seldom cut official releases from.

So, for example, we might have released M1 from the `master` branch, then we release B1, B2 and B3 from the `develop` branch. Then we release M2 from the `master` branch. 

When we generate release notes from M1 to M2, then all closed issues (in B1, B2 and B3) should be included.

Please contact @dpisklov for more information.

**Comment by dpisklov** [comment]
That's a bit inaccurate.
If the issues released in B1 were *not* cherrypicked/merged into master, they should *not* be in the M2 release notes.
In gren this is achieved by giving it "from" and "to" tags, btw.

**Comment by RobAustin** [comment]
@dpisklov let us assume that B1, B2 and B3 were merged back to master.
